#!/bin/bash
#SBATCH -p shared
#SBATCH --mem=40G
#SBATCH --job-name=gwas_post_qc_prep
#SBATCH -c 4
#SBATCH -o logs/o_gwas_post_qc_prep.txt
#SBATCH -e logs/e_gwas_post_qc_prep.txt
#SBATCH --mail-type=ALL

set -e

echo "**** Job starts: $(date) ****"

# Load required cluster software dependencies
module load vcftools
# module load perl

# 1. Download Will Rayner's alignment checking tool
if [ ! -f "HRC-1000G-check-bim.pl" ]; then
    wget http://www.well.ox.ac.uk/~wrayner/tools/HRC-1000G-check-bim.v4.2.5.zip
    unzip HRC-1000G-check-bim.v4.2.5.zip
fi

# 2. Generate frequency metrics from the finalized clean dataset
plink --bfile ${FILENAME}_final_clean --freq --out ${FILENAME}_final_clean --threads 4

# 3. Assess alignment strands against the reference panel
perl HRC-1000G-check-bim.pl \
     -b ${FILENAME}_final_clean.bim \
     -f ${FILENAME}_final_clean.frq \
     -r HRC.r1-1.GRCh37.wgs.mac5.sites.tab \
     -h

# 4. Execute the structural flipping script generated by the tool
sh Run-plink.sh

# 5 & 6. Loop to construct, sort, and compress clean VCF segments per chromosome
for chnum in {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23}; do
  
  # Recode to raw VCF
  plink --bfile YOURFILE-updated-chr$chnum \
        --recode vcf \
        --chr $chnum \
        --out YOURFILE_chr$chnum \
        --threads 4
        
  # Sort and coordinate block-compress using bgzip
  vcf-sort YOURFILE_chr$chnum.vcf | bgzip -c > pre_impute_YOURFILE_chr$chnum.vcf.gz
  
  # Remove temporary uncompressed VCF files to save allocation disk space
  rm YOURFILE_chr$chnum.vcf
done

echo "**** Job ends: $(date) ****"